// GENERATED by scraper/build-db.mjs — do not edit by hand.
export const DATA_BUNDLES: Record<string, number> = {
  en: require('../../assets/db/aion_en.db'),
  ru: require('../../assets/db/aion_ru.db'),
};
export const ASSETS_BUNDLE: number = require('../../assets/db/assets.db');
export const MANIFEST: Record<string, { size: number; builtAt: string }> = {
  "en": {
    "size": 43503616,
    "builtAt": "2026-09-07T08:15:19.703Z"
  },
  "ru": {
    "size": 50761728,
    "builtAt": "2026-09-07T08:14:48.372Z"
  },
  "assets": {
    "size": 42000384,
    "builtAt": "2026-09-07T01:21:10.149Z"
  }
};
export const DATA_LANGS = Object.keys(DATA_BUNDLES);
